apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    name: nginx
  clusterIP: None
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx
spec:
  hostname: master
  subdomain: default-subdomain
  containers:
  - image: nginx:latest
    command:
      - sleep
      - "3600"
    name: nginx

