apiVersion: v1
kind: ServiceAccount
metadata:
  name: newservice
  namespace: satya
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-for-pods
  namespace: satya
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebind
subjects:
- kind: ServiceAccount
  name: newservice
  namespace: satya
roleRef:
  kind: ClusterRole
  name: role-for-pods
  apiGroup: rbac.authorization.k8s.io

